name: Solar System Workflow
on:
    push

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_PASSWORD: SuperPassword
    MONGO_USERNAME: superuser

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
         
          - name: Setup NodeJS Version - 18
            uses: actions/setup-node@v3
            with:
                node-version: 18
         
          - name: Install Dependencies
            run: npm install
          
          - name: Unit Testing
            run: npm test

          - name: Archive Report
            uses: actions/upload-artifact@v4
            with:
                name: Mocha-Test-Result
                path: test-results.xml

    code-coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
         
          - name: Setup NodeJS Version - 18
            uses: actions/setup-node@v3
            with:
                node-version: 18
         
          - name: Install Dependencies
            run: npm install
          
          - name: Code Coverage
            continue-on-error: true
            run: npm run coverage

          - name: Archive Report
            uses: actions/upload-artifact@v4
            with:
                name: Code-Coverage-Results
                path: coverage
    docker:
      name: Run Docker
      runs-on: ubuntu-latest
      steps:
          - name: Docker Login
            uses: docker/login-action@v3
            with:
              username: ${{vars.DOCKER_USER}}
              password: ${{secrets.DOCKER_PASS}}
